### ISSUE TITLE
Create thoth extension in jupyter lab notebook tab [tracker]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#5]
As Data Scientist,

I want to manage dependencies directly from a notebook using an extension that lets me select these dependencies and install them in a specific kernel according to my requirements.

General
- [x] Set all requirements for jupyter lab extension Python package (https://github.com/thoth-station/jupyterlab-requirements/issues/16)
- [x] Create handlers for `requirements`, `requirements_lock`, `.thoth.yaml`, `install_packages`, `kernel`, `packages_installed` (server side) (https://github.com/thoth-station/jupyterlab-requirements/issues/14)
- [x] Create methods to handle `requirements`, `requirements_lock` and `.thoth.yaml` config in notebook metadata (get, embed, update, extract) (frontend side) (https://github.com/thoth-station/jupyterlab-requirements/issues/15)
- [x] Create UI to collect user inputs and show stored data.
- [x] Create a method for resolution engines to install requirements in the kernel
- [ ] Give option on the resolution engines
- [x] Use micropipenv to install dependencies created.
- [x] Automatically switch to new kernel after all dependencies are installed.
- [ ] Having options to modify .thoth.yaml specs

When starts and no dependencies are present:
- [x] Suggest that no dependencies are present (embedded), if they want to create/install them, just click here

When starts and notebook already exists;
- [x] Automatically detect dependencies embedded and install them in the kernel if user approves
- [x] Automatically identify different packages versions respect to the embedded one and ask for approval and recreation of the software stack in that case
- [x] Automatically identify different runtime than one stated in .thoth.yaml and ask for approval and recreation of the software stack in that case

**Comment by pacospace** [comment]
> As Data Scientist,
> 
> I want to manage dependencies directly from a notebook using an extension that lets me select these dependencies and install them in a specific kernel according to my requirements.
> 
> General
> 
> * [ ]  Having different resolution engines options
> * [ ]  Embed requirements, requirements_lock and .thoth.yaml config in notebook metadata
> * [ ]  Use micropipenv to install dependencies created by thoth.

instead of micropipenv, use thamos to install (micropipenv is part of thamos library now) See: https://github.com/thoth-station/thamos/blob/f7b3478caad34f14b391c801ea5b881692668612/thamos/cli.py#L336
```
from thamos.cli import install
install()
```

thanks @fridex for the guidance!

> * [ ]  Automatically switch to new kernel after all dependencies are installed
> * [ ]  Having options to modify .thoth.yaml specs
> 
> When starts and no dependencies are present:
> 
> * [ ]  Suggest that no dependencies are present (embedded), if they want to install them, just click here
> 
> When starts and notebook already exists;
> 
> * [ ]  Automatically identify different packages versions respect to the embedded one and and ask for approval and recreation of the software stack in that case
> * [ ]  Automatically identify different runtime than one stated in .thoth.yaml and ask for approval and recreation of the software stack in that case

**Comment by pacospace** [comment]
> As Data Scientist,
> 
> I want to manage dependencies directly from a notebook using an extension that lets me select these dependencies and install them in a specific kernel according to my requirements.
> 
> General
> 
> * [x]  Set all requirements for jupyter lab extension Python package (#16)
> * [x]  Create handlers for `requirements`, `requirements_lock`, `.thoth.yaml`, `install_packages`, `kernel`, `packages_installed` (server side) (#14)
> * [x]  Create methods to handle `requirements`, `requirements_lock` and `.thoth.yaml` config in notebook metadata (get, embed, update, extract) (frontend side) (#15)
> * [x]  Create UI to collect user inputs and show stored data.
> * [x]  Create a method for resolution engines to install requirements in the kernel
> * [ ]  Give option on the resolution engines
> * [x]  Use micropipenv to install dependencies created.
> * [x]  Automatically switch to new kernel after all dependencies are installed.
> * [ ]  Having options to modify .thoth.yaml specs
> 
> When starts and no dependencies are present:
> 
> * [x]  Suggest that no dependencies are present (embedded), if they want to create/install them, just click here
> 
> When starts and notebook already exists;
> 
> * [x]  Automatically detect dependencies embedded and install them in the kernel if user approves
> * [x]  Automatically identify different packages versions respect to the embedded one and ask for approval and recreation of the software stack in that case
> * [x]  Automatically identify different runtime than one stated in .thoth.yaml and ask for approval and recreation of the software stack in that case

This can be closed, remaining tasks, have been converted to issues/questions for feature features.
